from typing import Dict, List

API_DOCUMENTATION: List[Dict[str, object]] = [
    {
        "slug": "vendor-registration",
        "method": "POST",
        "path": "/v1/vendors/register",
        "title": {"en": "Vendor registration", "ru": "Регистрация продавца"},
        "description": {"en": "Creates a vendor record and returns a one-time API key; store the raw key securely.", "ru": "Создает продавца и возвращает одноразовый API-ключ, который нужно хранить безопасно."},
        "auth": {"en": "None", "ru": "Не требуется"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/vendors/register \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"name\":\"Acme\"}'", "ru": "curl -X POST http://localhost:8000/v1/vendors/register \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"name\":\"Acme\"}'"},
        "notes": {"en": "The raw key is shown once and stored in the database as a hash.", "ru": "Сырый ключ показывается один раз и сохраняется в базе в виде хеша."},
    },
    {
        "slug": "vendor-keys",
        "method": "POST",
        "path": "/v1/vendors/keys",
        "title": {"en": "Vendor API keys", "ru": "API-ключи продавца"},
        "description": {"en": "Issues a fresh API key for the logged-in vendor so credentials can rotate without downtime.", "ru": "Создает новый API-ключ для текущего продавца, чтобы обновлять доступ без простоя."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/vendors/keys \\\n  -H \"X-API-Key: <api_key>\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"label\":\"backup\"}'", "ru": "curl -X POST http://localhost:8000/v1/vendors/keys \\\n  -H \"X-API-Key: <api_key>\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"label\":\"backup\"}'"},
        "notes": {"en": "Rotate keys used by automation or dashboards without invalidating other tokens.", "ru": "Ротируйте ключи, которыми пользуются автоматизация или панели, не затрагивая остальные токены."},
    },
    {
        "slug": "vendor-revoke-key",
        "method": "POST",
        "path": "/v1/vendors/keys/{key_id}/revoke",
        "title": {"en": "Revoke vendor key", "ru": "Отозвать ключ продавца"},
        "description": {"en": "Revokes the specified key_id so it can no longer be used.", "ru": "Отзывает указанный ключ, чтобы он больше не работал."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/vendors/keys/123/revoke \\\n  -H \"X-API-Key: <api_key>\"", "ru": "curl -X POST http://localhost:8000/v1/vendors/keys/123/revoke \\\n  -H \"X-API-Key: <api_key>\""},
        "notes": {"en": "Send an optional reason to keep the audit trail clear.", "ru": "Можно указать причину, чтобы аудит был понятным."},
    },
    {
        "slug": "vendor-webhooks",
        "method": "POST",
        "path": "/v1/vendors/webhooks",
        "title": {"en": "Register webhook", "ru": "Регистрация webhook"},
        "description": {"en": "Registers a webhook that receives signed offer.created events for vendor offers with retries managed by the outbox.", "ru": "Регистрирует webhook, который получает подписанные события offer.created для офферов продавца и обрабатывается через outbox."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/vendors/webhooks \\\n  -H \"Content-Type: application/json\" \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\"url\":\"https://hooks.example.com/offer\",\"events\":[\"offer.created\"],\"secret\":\"s3cr3t\"}'", "ru": "curl -X POST http://localhost:8000/v1/vendors/webhooks \\\n  -H \"Content-Type: application/json\" \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\"url\":\"https://hooks.example.com/offer\",\"events\":[\"offer.created\"],\"secret\":\"s3cr3t\"}'"},
        "notes": {"en": "EventOutbox retries deliveries with exponential backoff before dead-lettering.", "ru": "EventOutbox повторно доставляет события с экспоненциальным бэкоффом до dead-letter."},
    },
    {
        "slug": "vendor-onboarding",
        "method": "GET",
        "path": "/v1/vendors/onboarding/status",
        "title": {"en": "Onboarding status", "ru": "Статус онбординга"},
        "description": {"en": "Summarizes whether you have an active API key and webhook so dashboards can guide next steps.", "ru": "Показывает, есть ли активный API-ключ и webhook, чтобы панель подсказала следующий шаг."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl http://localhost:8000/v1/vendors/onboarding/status \\\n  -H \"X-API-Key: <api_key>\"", "ru": "curl http://localhost:8000/v1/vendors/onboarding/status \\\n  -H \"X-API-Key: <api_key>\""},
        "notes": {"en": "Dashboard toggles warnings when this endpoint indicates missing pieces.", "ru": "Панель показывает предупреждения, если endpoint сообщает о пробелах."},
    },
    {
        "slug": "vendor-me",
        "method": "GET",
        "path": "/v1/vendors/me",
        "title": {"en": "Vendor profile", "ru": "Профиль продавца"},
        "description": {"en": "Returns the vendor identity tied to the supplied API key.", "ru": "Возвращает продавца, связанного с переданным ключом."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -H \"X-API-Key: <api_key>\" http://localhost:8000/v1/vendors/me", "ru": "curl -H \"X-API-Key: <api_key>\" http://localhost:8000/v1/vendors/me"},
        "notes": {"en": "Useful for verifying key scopes before sensitive actions.", "ru": "Полезно, чтобы проверить разрешения ключа перед важными действиями."},
    },
    {
        "slug": "vendor-profile-get",
        "method": "GET",
        "path": "/v1/vendors/me/profile",
        "title": {"en": "Vendor profile details", "ru": "Детали профиля продавца"},
        "description": {"en": "Returns the vendor profile used to match buyer requests.", "ru": "Возвращает профиль продавца, который используется для подбора запросов покупателя."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -H \"X-API-Key: <api_key>\" http://localhost:8000/v1/vendors/me/profile", "ru": "curl -H \"X-API-Key: <api_key>\" http://localhost:8000/v1/vendors/me/profile"},
        "notes": {"en": "Use this endpoint to preview matching criteria in the dashboard.", "ru": "Используйте этот endpoint, чтобы проверить критерии матчинга в панели."},
    },
    {
        "slug": "vendor-profile-update",
        "method": "PUT",
        "path": "/v1/vendors/me/profile",
        "title": {"en": "Update vendor profile", "ru": "Обновить профиль продавца"},
        "description": {"en": "Upserts the vendor profile payload for matching buyer requests.", "ru": "Создает или обновляет профиль продавца для подбора запросов покупателя."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -X PUT http://localhost:8000/v1/vendors/me/profile \\\n  -H \"Content-Type: application/json\" \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\"categories\":[\"sneakers\"],\"regions\":[\"EU\"]}'", "ru": "curl -X PUT http://localhost:8000/v1/vendors/me/profile \\\n  -H \"Content-Type: application/json\" \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\"categories\":[\"sneakers\"],\"regions\":[\"EU\"]}'"},
        "notes": {"en": "Provide categories, regions, and lead times so matching can score buyer requests.", "ru": "Укажите категории, регионы и сроки, чтобы матчингу было с чем работать."},
    },
    {
        "slug": "buyer-registration",
        "method": "POST",
        "path": "/v1/buyers/register",
        "title": {"en": "Buyer registration", "ru": "Регистрация покупателя"},
        "description": {"en": "Issues a buyer-scoped API key that must be sent in X-Buyer-API-Key for future calls.", "ru": "Выдает buyer-ключ, который нужно передавать в заголовке X-Buyer-API-Key."},
        "auth": {"en": "None", "ru": "Не требуется"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/buyers/register \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"name\":\"Acme Buyer\"}'", "ru": "curl -X POST http://localhost:8000/v1/buyers/register \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"name\":\"Acme Buyer\"}'"},
        "notes": {"en": "Buyer tokens let buyers pull rankings without vendor privileges.", "ru": "Токены покупателя позволяют получать ранжирование без доступа продавца."},
    },
    {
        "slug": "buyer-me",
        "method": "GET",
        "path": "/v1/buyers/me",
        "title": {"en": "Buyer profile", "ru": "Профиль покупателя"},
        "description": {"en": "Mirrors /v1/vendors/me so buyers can verify their identity.", "ru": "Аналогично /v1/vendors/me, чтобы покупатель проверил себя."},
        "auth": {"en": "X-Buyer-API-Key required", "ru": "Требуется X-Buyer-API-Key"},
        "example": {"en": "curl -H \"X-Buyer-API-Key: <buyer_key>\" http://localhost:8000/v1/buyers/me", "ru": "curl -H \"X-Buyer-API-Key: <buyer_key>\" http://localhost:8000/v1/buyers/me"},
        "notes": {"en": "Returns the registered buyer record for audits.", "ru": "Возвращает запись покупателя для аудита."},
    },
    {
        "slug": "buyer-ranking",
        "method": "GET",
        "path": "/v1/buyers/rfo/{rfo_id}/ranking",
        "title": {"en": "Buyer ranking", "ru": "Ранжирование для покупателя"},
        "description": {"en": "Returns every vendor offer for the buyer request (RFO) together with score and explain payload.", "ru": "Отдает все офферы продавца по запросу покупателя (RFO) с оценкой и explain payload."},
        "auth": {"en": "X-Buyer-API-Key required", "ru": "Требуется X-Buyer-API-Key"},
        "example": {"en": "curl -H \"X-Buyer-API-Key: <buyer_key>\" http://localhost:8000/v1/buyers/rfo/1/ranking", "ru": "curl -H \"X-Buyer-API-Key: <buyer_key>\" http://localhost:8000/v1/buyers/rfo/1/ranking"},
        "notes": {"en": "Designed for buyers to audit the ranking algorithm.", "ru": "Предназначено для аудита алгоритма ранжирования покупателем."},
    },
    {
        "slug": "buyer-rfo-list",
        "method": "GET",
        "path": "/v1/buyers/rfos",
        "title": {"en": "Buyer request list", "ru": "Список запросов покупателя"},
        "description": {"en": "Lists buyer requests (RFOs) owned by the authenticated buyer.", "ru": "Возвращает запросы покупателя (RFO), принадлежащие текущему покупателю."},
        "auth": {"en": "X-Buyer-API-Key required", "ru": "Требуется X-Buyer-API-Key"},
        "example": {"en": "curl -H \"X-Buyer-API-Key: <buyer_key>\" http://localhost:8000/v1/buyers/rfos", "ru": "curl -H \"X-Buyer-API-Key: <buyer_key>\" http://localhost:8000/v1/buyers/rfos"},
        "notes": {"en": "Use this endpoint for buyer dashboards and saved views.", "ru": "Используйте этот endpoint для панели покупателя и сохраненных подборок."},
    },
    {
        "slug": "rfo-create",
        "method": "POST",
        "path": "/v1/rfo",
        "title": {"en": "Create RFO", "ru": "Создать RFO"},
        "description": {"en": "Creates a buyer request (RFO) with constraints and weighted preferences.", "ru": "Создает запрос покупателя (RFO) с ограничениями и весами предпочтений."},
        "auth": {"en": "None", "ru": "Не требуется"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/rfo \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n    \"category\": \"sneakers\",\n    \"constraints\": {\"budget_max\": 120, \"size\": 42, \"delivery_deadline_days\": 3},\n    \"preferences\": {\"w_price\": 0.6, \"w_delivery\": 0.3, \"w_warranty\": 0.1}\n  }'", "ru": "curl -X POST http://localhost:8000/v1/rfo \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n    \"category\": \"sneakers\",\n    \"constraints\": {\"budget_max\": 120, \"size\": 42, \"delivery_deadline_days\": 3},\n    \"preferences\": {\"w_price\": 0.6, \"w_delivery\": 0.3, \"w_warranty\": 0.1}\n  }'"},
        "notes": {"en": "Use this endpoint to refresh the marketplace with new intent data.", "ru": "Используйте этот endpoint, чтобы обновлять рынок с новыми RFO."},
    },
    {
        "slug": "rfo-list",
        "method": "GET",
        "path": "/v1/rfo",
        "title": {"en": "List buyer requests", "ru": "Список запросов покупателя"},
        "description": {"en": "Lists buyer requests (RFOs) with filters for status, category, budget, and deadline.", "ru": "Возвращает список запросов покупателя (RFO) с фильтрами по статусу, категории, бюджету и сроку."},
        "auth": {"en": "None", "ru": "Не требуется"},
        "example": {"en": "curl \"http://localhost:8000/v1/rfo?status=OPEN&category=sneakers\"", "ru": "curl \"http://localhost:8000/v1/rfo?status=OPEN&category=sneakers\""},
        "notes": {"en": "Use pagination params to control page size and offset.", "ru": "Используйте параметры пагинации для управления размером и смещением."},
    },
    {
        "slug": "rfo-detail",
        "method": "GET",
        "path": "/v1/rfo/{id}",
        "title": {"en": "RFO details", "ru": "Детали RFO"},
        "description": {"en": "Returns the buyer request (RFO) plus the current vendor offer count.", "ru": "Возвращает запрос покупателя (RFO) и количество офферов продавца."},
        "auth": {"en": "None", "ru": "Не требуется"},
        "example": {"en": "curl http://localhost:8000/v1/rfo/1", "ru": "curl http://localhost:8000/v1/rfo/1"},
        "notes": {"en": "", "ru": ""},
    },
    {
        "slug": "rfo-best",
        "method": "GET",
        "path": "/v1/rfo/{id}/best",
        "title": {"en": "Best offers", "ru": "Лучшие офферы"},
        "description": {"en": "Returns the top vendor offers for a buyer request with score breakdowns via the explain field.", "ru": "Отдает лучшие офферы продавцов по запросу покупателя с разбивкой скоринга в explain."},
        "auth": {"en": "None", "ru": "Не требуется"},
        "example": {"en": "curl \"http://localhost:8000/v1/rfo/1/best?top_k=3\"", "ru": "curl \"http://localhost:8000/v1/rfo/1/best?top_k=3\""},
        "notes": {"en": "Set top_k to tune how many responses you inspect.", "ru": "Укажите top_k, чтобы контролировать количество ответов."},
    },
    {
        "slug": "offer-create",
        "method": "POST",
        "path": "/v1/offers",
        "title": {"en": "Submit offer", "ru": "Отправить оффер"},
        "description": {"en": "Uploads a vendor offer for an open buyer request (RFO) and runs validation before scoring.", "ru": "Отправляет оффер продавца для открытого запроса покупателя (RFO) и проверяет данные перед скорингом."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/offers \\\n  -H \"Content-Type: application/json\" \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\n    \"rfo_id\": 1,\n    \"price_amount\": 109.99,\n    \"currency\": \"USD\",\n    \"delivery_eta_days\": 2,\n    \"warranty_months\": 12,\n    \"return_days\": 30,\n    \"stock\": true,\n    \"metadata\": {\"sku\": \"ABC\"}\n  }'", "ru": "curl -X POST http://localhost:8000/v1/offers \\\n  -H \"Content-Type: application/json\" \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\n    \"rfo_id\": 1,\n    \"price_amount\": 109.99,\n    \"currency\": \"USD\",\n    \"delivery_eta_days\": 2,\n    \"warranty_months\": 12,\n    \"return_days\": 30,\n    \"stock\": true,\n    \"metadata\": {\"sku\": \"ABC\"}\n  }'"},
        "notes": {"en": "Validation enforces price, warranty, and cooldown limits.", "ru": "Валидация контролирует цену, гарантию и кулдаун."},
    },
    {
        "slug": "vendor-offers-list",
        "method": "GET",
        "path": "/v1/vendors/me/offers",
        "title": {"en": "Vendor offers list", "ru": "Список офферов продавца"},
        "description": {"en": "Lists vendor offers submitted by the authenticated vendor with a buyer request summary.", "ru": "Возвращает офферы продавца для текущего продавца с кратким описанием запроса покупателя."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -H \"X-API-Key: <api_key>\" http://localhost:8000/v1/vendors/me/offers", "ru": "curl -H \"X-API-Key: <api_key>\" http://localhost:8000/v1/vendors/me/offers"},
        "notes": {"en": "Use this for vendor dashboards and performance tracking.", "ru": "Используйте этот endpoint для панели продавца и мониторинга результатов."},
    },
    {
        "slug": "rfo-close",
        "method": "POST",
        "path": "/v1/rfo/{id}/close",
        "title": {"en": "Close RFO", "ru": "Закрыть RFO"},
        "description": {"en": "Transitions the buyer request (RFO) from OPEN to CLOSED and prevents new vendor offers.", "ru": "Переводит запрос покупателя (RFO) из OPEN в CLOSED и блокирует новые офферы продавца."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/rfo/1/close \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\"reason\":\"deadline met\"}'", "ru": "curl -X POST http://localhost:8000/v1/rfo/1/close \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\"reason\":\"deadline met\"}'"},
        "notes": {"en": "Changes are logged to audit_log with the optional reason.", "ru": "Действие записывается в audit_log вместе с причиной, если она есть."},
    },
    {
        "slug": "rfo-award",
        "method": "POST",
        "path": "/v1/rfo/{id}/award",
        "title": {"en": "Award offer", "ru": "Выбрать победителя"},
        "description": {"en": "Marks a vendor offer as the winner and moves the buyer request (RFO) to AWARDED.", "ru": "Выбирает оффер продавца и переводит запрос покупателя (RFO) в AWARDED."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/rfo/1/award \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\"offer_id\": 42}'", "ru": "curl -X POST http://localhost:8000/v1/rfo/1/award \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\"offer_id\": 42}'"},
        "notes": {"en": "Ensure the chosen offer belongs to the RFO before awarding.", "ru": "Проверьте, что оффер принадлежит текущему RFO, прежде чем выбирать его."},
    },
    {
        "slug": "rfo-reopen",
        "method": "POST",
        "path": "/v1/rfo/{id}/reopen",
        "title": {"en": "Reopen RFO", "ru": "Переоткрыть RFO"},
        "description": {"en": "Reopens a CLOSED/AWARDED buyer request (RFO) where business rules allow it.", "ru": "Повторно открывает CLOSED/AWARDED запрос покупателя (RFO), если правила позволяют."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/rfo/1/reopen \\\n  -H \"X-API-Key: <api_key>\"", "ru": "curl -X POST http://localhost:8000/v1/rfo/1/reopen \\\n  -H \"X-API-Key: <api_key>\""},
        "notes": {"en": "The endpoint is idempotent and logs every transition.", "ru": "Эндпоинт идемпотентен и записывает каждое изменение статуса."},
    },
    {
        "slug": "rfo-scoring",
        "method": "POST",
        "path": "/v1/rfo/{id}/scoring",
        "title": {"en": "Update scoring", "ru": "Обновить скоринг"},
        "description": {"en": "Updates the scoring_version and per-component weights for a buyer request (RFO).", "ru": "Обновляет scoring_version и веса компонентов для запроса покупателя (RFO)."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl -X POST http://localhost:8000/v1/rfo/1/scoring \\\n  -H \"Content-Type: application/json\" \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\"scoring_version\":\"v2\",\"weights\":{\"w_price\":0.5,\"w_delivery\":0.3,\"w_warranty\":0.2}}'", "ru": "curl -X POST http://localhost:8000/v1/rfo/1/scoring \\\n  -H \"Content-Type: application/json\" \\\n  -H \"X-API-Key: <api_key>\" \\\n  -d '{\"scoring_version\":\"v2\",\"weights\":{\"w_price\":0.5,\"w_delivery\":0.3,\"w_warranty\":0.2}}'"},
        "notes": {"en": "Lock a scoring version for auditability while tweaking component weights.", "ru": "Фиксируйте версию скоринга для аудита, меняя веса компонентов."},
    },
    {
        "slug": "rfo-ranking-explain",
        "method": "GET",
        "path": "/v1/rfo/{id}/ranking/explain",
        "title": {"en": "Ranking explain", "ru": "Объяснение ранжирования"},
        "description": {"en": "Shows the resolved scoring version, component breakdown, and active penalties for a buyer request (RFO).", "ru": "Показывает версию скоринга, разбивку по компонентам и активные штрафы для запроса покупателя (RFO)."},
        "auth": {"en": "X-API-Key required", "ru": "Требуется X-API-Key"},
        "example": {"en": "curl http://localhost:8000/v1/rfo/1/ranking/explain", "ru": "curl http://localhost:8000/v1/rfo/1/ranking/explain"},
        "notes": {"en": "Ideal for audits and debugging scoring decisions.", "ru": "Удобно для аудита и отладки решений скоринга."},
    },
]

def _translate(doc: Dict[str, object], language: str) -> Dict[str, str]:
    return {
        "slug": doc["slug"],
        "method": doc["method"],
        "path": doc["path"],
        "title": doc["title"][language],
        "description": doc["description"][language],
        "auth": doc["auth"][language],
        "example": doc["example"][language],
        "notes": doc.get("notes", {}).get(language, ""),
    }

def list_api_docs(language: str = "en") -> List[Dict[str, str]]:
    return [_translate(doc, language) for doc in API_DOCUMENTATION]

def get_api_doc(slug: str, language: str = "en") -> Dict[str, str]:
    for doc in API_DOCUMENTATION:
        if doc["slug"] == slug:
            return _translate(doc, language)
    raise KeyError(f"API doc not found: {slug}")
